version: "3"
services:
    www-php:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html/
        links:
            - database
        networks:
            - app

    database:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./_docker/db:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=open_pet
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        networks:
            - app
networks:
  app:
    driver: bridge